In [40]:
from pyntcloud import PyntCloud
import numpy as np
import pandas as pd

In [116]:
filename1 = "../data/room_data_1200rpm.csv"
filename2 = "../data/room_data_300rpm.csv"

cloud1 = PyntCloud.from_file(filename1)
cloud = PyntCloud.from_file(filename2)

In [117]:
cloud1

PyntCloud
11062 points with 10 scalar fields
0 faces in mesh
0 kdtrees
0 voxelgrids
Centroid: -0.17834323584912312, 1.137226996881034, 0.06999669731703129
Other attributes:

In [121]:
cloud

PyntCloud
45068 points with 10 scalar fields
0 faces in mesh
0 kdtrees
0 voxelgrids
Centroid: -0.2170131432466939, 1.1557290857042026, 0.07099850993634065
Other attributes:

In [122]:
# cloud1.plot(point_size=0.01,use_as_color='intensity', cmap='Reds', output_name="1200rpm_plot")
# cloud2.plot(point_size=0.01,use_as_color='intensity', cmap='Reds', output_name="300rpm_plot")

In [123]:
def channel_order(number):
    return {
        0 : 0,
        1 : 2,
        2 : 4,
        3 : 6,
        4 : 8,
        5 : 10,
        6 : 12,
        7 : 14,
        8 : 1,
        9 : 3,
        10 : 5,
        11 : 7,
        12 : 9,
        13 : 11,
        14 : 13,
        15 : 15
    }[number]

In [124]:
def make_pharma(number,head,tail):
    a = bin(12)
    a = list(a[2:])
    np.asarray(a,dtype=int)

    head = np.asarray([1,1,0],dtype=int)
    tail = np.asarray([0,1,1],dtype=int)

    middle = np.append(head,a)
    final = np.append(middle,tail)
    return final

Print Code Overview

    - add is_code column
    - get location of the column
    - get length of pharma_list
    - channel_index = np.where(cloud.points.laser_id == 0)[0]
        - this gets array of all indices that are part of this mask
    - get array with indices the length of the pharma_list
    - np.where(channel_index == index_origin)[0][0]
        - this gets me the index in the channel_index array where the closest location to desired location starts
    - using iloc and the column location replace the values into the is_code column



In [163]:
channel_mask = cloud.points.laser_id == 9
cloud.points.loc[channel_mask]

channel_index = np.where(cloud.points.laser_id == 0)[0]
channel_index

array([    0,    16,    32, ..., 45021, 45036, 45052])

In [177]:
chosen_idx = 22500
for item in channel_index:
    if abs(item - chosen_idx) < 8:
        index_origin = item
        print(index_origin)

pharma_list = make_pharma(12,[1,1,0], [0,1,1])
pharma_index_origin = np.where(channel_index == index_origin)[0][0]

pharma_index = channel_index[pharma_index_origin:(pharma_index_origin + len(pharma_list))]
pharma_index

cloud.points

22495


array([22495, 22511, 22527, 22541, 22557, 22572, 22588, 22603, 22619,
       22634])

In [176]:
np.where(channel_index == index_origin)[0][0]
channel_index[1361:(1361 + 12)]

array([22495, 22511, 22527, 22541, 22557, 22572, 22588, 22603, 22619,
       22634, 22649, 22665])

In [196]:
num_cols = len(cloud.points.columns)
#cloud.points.insert(loc=num_cols, column='is_code', value=0)
is_code_col = cloud.points.columns.get_loc('is_code')
cloud.points.iloc[pharma_index,is_]

22495   -0.468192
22511   -0.460895
22527   -0.453610
22541   -0.456636
22557   -0.463084
22572   -0.460993
22588   -0.455437
22603   -0.455021
22619   -0.458022
22634   -0.464430
Name: Points_m_XYZ:1, dtype: float64